---
abstract: "SYP's Dist::Zilla minting profile"
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300026, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-MintingProfile-SYP
requires:
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Moose: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Dist-Zilla-MintingProfile-SYP/issues
  homepage: https://github.com/creaktive/Dist-Zilla-MintingProfile-SYP
  repository: git://github.com/creaktive/Dist-Zilla-MintingProfile-SYP.git
version: 0.004
